import { mkdir, rm, symlink, writeFile } from 'node:fs/promises'
import { createHash } from 'node:crypto'
import { dirname, join, resolve, sep } from 'node:path'
import type { PatchArtifact } from '../git/patches.ts'
import { assertOwnedPaths } from '../git/ownership.ts'
import { assertRepoPathsConfined } from '../git/repository.ts'
export function needsIntegrator(taskCount:number,hasWorktreePatch:boolean,crossTaskWiring:boolean,conflict:boolean){return !(taskCount===1&&!hasWorktreePatch&&!crossTaskWiring&&!conflict)}
function verifyPatch(patch:PatchArtifact){const {sha256,...raw}=patch;const actual=createHash('sha256').update(JSON.stringify(raw)).digest('hex');if(actual!==sha256)throw new Error(`patch artifact hash mismatch for ${patch.taskId}`);for(const f of patch.files)if(f.kind==='file'){const bytes=Buffer.from(f.contentBase64??'','base64'),hash=createHash('sha256').update(bytes).digest('hex');if(hash!==f.sha256)throw new Error(`patch file hash mismatch: ${f.path}`)}}
function assertSymlinkTarget(root:string,path:string,target:string){if(!target)throw new Error(`empty symlink target: ${path}`);const b=resolve(root),resolved=resolve(dirname(join(b,path)),target);if(resolved!==b&&!resolved.startsWith(b+sep))throw new Error(`symlink target escapes repository: ${path} -> ${target}`)}
export async function applyPatchArtifact(root:string,patch:PatchArtifact,unionOwnership:string[]){verifyPatch(patch);const paths=patch.files.map(f=>f.path);assertOwnedPaths(paths,unionOwnership);await assertRepoPathsConfined(root,paths);for(const f of patch.files){const target=join(root,f.path);if(f.kind==='delete'){await rm(target,{force:true});continue}await mkdir(dirname(target),{recursive:true});if(f.kind==='symlink'){assertSymlinkTarget(root,f.path,f.target!);await rm(target,{force:true});await symlink(f.target!,target);continue}await writeFile(target,Buffer.from(f.contentBase64!,'base64'))}}
export function integratorPrompt(planJson:string,handoffs:string[],patchLocators:string[]){return `Role: Integrator\nDo not redesign or expand scope. You may modify only union ownership. Account for every accepted Worker patch; missing/ambiguous artifacts are BLOCKED. Never commit/push/reset/clean.\n\nAuthoritative PlanArtifact:\n${planJson}\n\nBounded handoff:\n${handoffs.join('\n')}\n\nPatch locators:\n${patchLocators.join('\n')}`}
